function summarize_metrics(M)
% Prints a compact, readable summary line.
fprintf(['IV=%.3g,  A_p=%.3g,  H=%.3g,  U_D=%.3g,  ', ...
         'E[Δ]=%.3g (±%.3g),  EIVR=%.3g,  ', ...
         '||g||_1=%.3g,  ||g_D||_1=%.3g,  max|g_D|=%.3g,  ', ...
         's2*=%.3g,  d_min(std)=%.3g,  time=%.2fs\n'], ...
        M.IV, M.A_p, M.H_band, M.U_D, ...
        M.EDelta_best, M.EDelta_std, M.EIVR, ...
        M.g_norm1, M.gD_norm1, M.gD_max, ...
        M.s2_candidate, M.min_dist_std, M.time_scoring);
end