function gpr_model = train_gpr_model(X_train, Y_train)
    gpr_model = fitrgp(X_train, Y_train, ...
        'KernelFunction', 'squaredexponential', ...
        'Standardize', true, ...
        'FitMethod', 'none', ...
        'PredictMethod', 'exact');
end
